//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emplooye
    {
        public int EmplooyeId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmplooyeTC { get; set; }
        public string EmplooyeName { get; set; }
        public string EmplooyeSurname { get; set; }
        public string DateOfBirth { get; set; }
        public string GenderId { get; set; }
        public string StartDate { get; set; }
        public string FinishDate { get; set; }
    }
}
