//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSale
    {
        public int SaleId { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<int> TotalTicket { get; set; }
        public string MovieId { get; set; }
        public string DateOfPurchase { get; set; }
    }
}
