//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _PresentationLayer.BiletSatisServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiletSatisServiceReference.IBiletSatisi")]
    public interface IBiletSatisi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/KategoriEkle", ReplyAction="http://tempuri.org/IBiletSatisi/KategoriEkleResponse")]
        void KategoriEkle(string customerPhone, string totalTicket, string movieId, string dateofPurchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/KategoriEkle", ReplyAction="http://tempuri.org/IBiletSatisi/KategoriEkleResponse")]
        System.Threading.Tasks.Task KategoriEkleAsync(string customerPhone, string totalTicket, string movieId, string dateofPurchase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/TicketSaleDelete", ReplyAction="http://tempuri.org/IBiletSatisi/TicketSaleDeleteResponse")]
        _BusinessLayer.Model.Status TicketSaleDelete(_DataLayer.TicketSale ticketsale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/TicketSaleDelete", ReplyAction="http://tempuri.org/IBiletSatisi/TicketSaleDeleteResponse")]
        System.Threading.Tasks.Task<_BusinessLayer.Model.Status> TicketSaleDeleteAsync(_DataLayer.TicketSale ticketsale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/TicketSaleUpdate", ReplyAction="http://tempuri.org/IBiletSatisi/TicketSaleUpdateResponse")]
        _BusinessLayer.Model.Status TicketSaleUpdate(_DataLayer.TicketSale ticketsale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/TicketSaleUpdate", ReplyAction="http://tempuri.org/IBiletSatisi/TicketSaleUpdateResponse")]
        System.Threading.Tasks.Task<_BusinessLayer.Model.Status> TicketSaleUpdateAsync(_DataLayer.TicketSale ticketsale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/TicketAsJson", ReplyAction="http://tempuri.org/IBiletSatisi/TicketAsJsonResponse")]
        _DataLayer.TicketSale[] TicketAsJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiletSatisi/TicketAsJson", ReplyAction="http://tempuri.org/IBiletSatisi/TicketAsJsonResponse")]
        System.Threading.Tasks.Task<_DataLayer.TicketSale[]> TicketAsJsonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBiletSatisiChannel : _PresentationLayer.BiletSatisServiceReference.IBiletSatisi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiletSatisiClient : System.ServiceModel.ClientBase<_PresentationLayer.BiletSatisServiceReference.IBiletSatisi>, _PresentationLayer.BiletSatisServiceReference.IBiletSatisi {
        
        public BiletSatisiClient() {
        }
        
        public BiletSatisiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiletSatisiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiletSatisiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiletSatisiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void KategoriEkle(string customerPhone, string totalTicket, string movieId, string dateofPurchase) {
            base.Channel.KategoriEkle(customerPhone, totalTicket, movieId, dateofPurchase);
        }
        
        public System.Threading.Tasks.Task KategoriEkleAsync(string customerPhone, string totalTicket, string movieId, string dateofPurchase) {
            return base.Channel.KategoriEkleAsync(customerPhone, totalTicket, movieId, dateofPurchase);
        }
        
        public _BusinessLayer.Model.Status TicketSaleDelete(_DataLayer.TicketSale ticketsale) {
            return base.Channel.TicketSaleDelete(ticketsale);
        }
        
        public System.Threading.Tasks.Task<_BusinessLayer.Model.Status> TicketSaleDeleteAsync(_DataLayer.TicketSale ticketsale) {
            return base.Channel.TicketSaleDeleteAsync(ticketsale);
        }
        
        public _BusinessLayer.Model.Status TicketSaleUpdate(_DataLayer.TicketSale ticketsale) {
            return base.Channel.TicketSaleUpdate(ticketsale);
        }
        
        public System.Threading.Tasks.Task<_BusinessLayer.Model.Status> TicketSaleUpdateAsync(_DataLayer.TicketSale ticketsale) {
            return base.Channel.TicketSaleUpdateAsync(ticketsale);
        }
        
        public _DataLayer.TicketSale[] TicketAsJson() {
            return base.Channel.TicketAsJson();
        }
        
        public System.Threading.Tasks.Task<_DataLayer.TicketSale[]> TicketAsJsonAsync() {
            return base.Channel.TicketAsJsonAsync();
        }
    }
}
