//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _PresentationLayer.TurServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TurServiceReference.ITur")]
    public interface ITur {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITur/GenderAsJson", ReplyAction="http://tempuri.org/ITur/GenderAsJsonResponse")]
        _DataLayer.Genre[] GenderAsJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITur/GenderAsJson", ReplyAction="http://tempuri.org/ITur/GenderAsJsonResponse")]
        System.Threading.Tasks.Task<_DataLayer.Genre[]> GenderAsJsonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITurChannel : _PresentationLayer.TurServiceReference.ITur, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TurClient : System.ServiceModel.ClientBase<_PresentationLayer.TurServiceReference.ITur>, _PresentationLayer.TurServiceReference.ITur {
        
        public TurClient() {
        }
        
        public TurClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TurClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TurClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _DataLayer.Genre[] GenderAsJson() {
            return base.Channel.GenderAsJson();
        }
        
        public System.Threading.Tasks.Task<_DataLayer.Genre[]> GenderAsJsonAsync() {
            return base.Channel.GenderAsJsonAsync();
        }
    }
}
