//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _PresentationLayer.FilmServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FilmServiceReference.IFilm")]
    public interface IFilm {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieAdd", ReplyAction="http://tempuri.org/IFilm/MovieAddResponse")]
        _BusinessLayer.Model.Status MovieAdd(_DataLayer.Movy movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieAdd", ReplyAction="http://tempuri.org/IFilm/MovieAddResponse")]
        System.Threading.Tasks.Task<_BusinessLayer.Model.Status> MovieAddAsync(_DataLayer.Movy movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieDelete", ReplyAction="http://tempuri.org/IFilm/MovieDeleteResponse")]
        _BusinessLayer.Model.Status MovieDelete(_DataLayer.Movy movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieDelete", ReplyAction="http://tempuri.org/IFilm/MovieDeleteResponse")]
        System.Threading.Tasks.Task<_BusinessLayer.Model.Status> MovieDeleteAsync(_DataLayer.Movy movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieUpdate", ReplyAction="http://tempuri.org/IFilm/MovieUpdateResponse")]
        _BusinessLayer.Model.Status MovieUpdate(_DataLayer.Movy movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieUpdate", ReplyAction="http://tempuri.org/IFilm/MovieUpdateResponse")]
        System.Threading.Tasks.Task<_BusinessLayer.Model.Status> MovieUpdateAsync(_DataLayer.Movy movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/filmbul", ReplyAction="http://tempuri.org/IFilm/filmbulResponse")]
        _BusinessLayer.Model.MovieRestList[] filmbul(string filmadi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/filmbul", ReplyAction="http://tempuri.org/IFilm/filmbulResponse")]
        System.Threading.Tasks.Task<_BusinessLayer.Model.MovieRestList[]> filmbulAsync(string filmadi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieAsJson", ReplyAction="http://tempuri.org/IFilm/MovieAsJsonResponse")]
        _BusinessLayer.Model.MovieRestList[] MovieAsJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/MovieAsJson", ReplyAction="http://tempuri.org/IFilm/MovieAsJsonResponse")]
        System.Threading.Tasks.Task<_BusinessLayer.Model.MovieRestList[]> MovieAsJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/First", ReplyAction="http://tempuri.org/IFilm/FirstResponse")]
        _DataLayer.SP_GetMovieByGender_Result[] First(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilm/First", ReplyAction="http://tempuri.org/IFilm/FirstResponse")]
        System.Threading.Tasks.Task<_DataLayer.SP_GetMovieByGender_Result[]> FirstAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFilmChannel : _PresentationLayer.FilmServiceReference.IFilm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilmClient : System.ServiceModel.ClientBase<_PresentationLayer.FilmServiceReference.IFilm>, _PresentationLayer.FilmServiceReference.IFilm {
        
        public FilmClient() {
        }
        
        public FilmClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilmClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilmClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilmClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _BusinessLayer.Model.Status MovieAdd(_DataLayer.Movy movie) {
            return base.Channel.MovieAdd(movie);
        }
        
        public System.Threading.Tasks.Task<_BusinessLayer.Model.Status> MovieAddAsync(_DataLayer.Movy movie) {
            return base.Channel.MovieAddAsync(movie);
        }
        
        public _BusinessLayer.Model.Status MovieDelete(_DataLayer.Movy movie) {
            return base.Channel.MovieDelete(movie);
        }
        
        public System.Threading.Tasks.Task<_BusinessLayer.Model.Status> MovieDeleteAsync(_DataLayer.Movy movie) {
            return base.Channel.MovieDeleteAsync(movie);
        }
        
        public _BusinessLayer.Model.Status MovieUpdate(_DataLayer.Movy movie) {
            return base.Channel.MovieUpdate(movie);
        }
        
        public System.Threading.Tasks.Task<_BusinessLayer.Model.Status> MovieUpdateAsync(_DataLayer.Movy movie) {
            return base.Channel.MovieUpdateAsync(movie);
        }
        
        public _BusinessLayer.Model.MovieRestList[] filmbul(string filmadi) {
            return base.Channel.filmbul(filmadi);
        }
        
        public System.Threading.Tasks.Task<_BusinessLayer.Model.MovieRestList[]> filmbulAsync(string filmadi) {
            return base.Channel.filmbulAsync(filmadi);
        }
        
        public _BusinessLayer.Model.MovieRestList[] MovieAsJson() {
            return base.Channel.MovieAsJson();
        }
        
        public System.Threading.Tasks.Task<_BusinessLayer.Model.MovieRestList[]> MovieAsJsonAsync() {
            return base.Channel.MovieAsJsonAsync();
        }
        
        public _DataLayer.SP_GetMovieByGender_Result[] First(string name) {
            return base.Channel.First(name);
        }
        
        public System.Threading.Tasks.Task<_DataLayer.SP_GetMovieByGender_Result[]> FirstAsync(string name) {
            return base.Channel.FirstAsync(name);
        }
    }
}
