//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _PresentationLayer.CinsiyetServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CinsiyetServiceReference.ICinsiyet")]
    public interface ICinsiyet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinsiyet/GenderAsJson", ReplyAction="http://tempuri.org/ICinsiyet/GenderAsJsonResponse")]
        _DataLayer.Gender[] GenderAsJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICinsiyet/GenderAsJson", ReplyAction="http://tempuri.org/ICinsiyet/GenderAsJsonResponse")]
        System.Threading.Tasks.Task<_DataLayer.Gender[]> GenderAsJsonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICinsiyetChannel : _PresentationLayer.CinsiyetServiceReference.ICinsiyet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CinsiyetClient : System.ServiceModel.ClientBase<_PresentationLayer.CinsiyetServiceReference.ICinsiyet>, _PresentationLayer.CinsiyetServiceReference.ICinsiyet {
        
        public CinsiyetClient() {
        }
        
        public CinsiyetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CinsiyetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinsiyetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinsiyetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _DataLayer.Gender[] GenderAsJson() {
            return base.Channel.GenderAsJson();
        }
        
        public System.Threading.Tasks.Task<_DataLayer.Gender[]> GenderAsJsonAsync() {
            return base.Channel.GenderAsJsonAsync();
        }
    }
}
